project:
  title: "Sample Book"
  type: book
  output-dir: docs


book:
  title: "This is a book"
  chapters:
    - index.qmd
    - gridpost.qmd

format:
  html:
    theme: flatly
    embed-resources: true
    standalone: true
  docx:
    fig-align: right
    toc: true
    standalone: true
    extract-media: images
    from: html
  pdf:
    mainfont: "Georgia"
    
    










